name: taroting
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  chat_gpt_flutter: ^1.0.10
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.7+4
  meta: ^1.8.0
  sharedor: 
    path: ../sharedor
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite