name: taroting
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  camera: ^0.10.5+2
  chat_gpt_flutter: ^1.0.10
  firebase_core: ^1.10.0
  firebase_storage: ^10.3.11
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_tflite: ^1.0.1
  image: ^3.3.0
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+4
  meta: ^1.8.0
  sharedor: 
    path: ../sharedor
  # tflite: ^1.1.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MartelSans
      fonts: 
      - asset: assets/fonts/MartelSans-Regular.ttf
    # - family: ZodiacSigns
    #   fonts: 
    #   - asset: assets/fonts/ZodiacSigns.ttf  
  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite
    - assets/cards/
    - assets/camera-overlay-conceptcoder.png
    - assets/images/
dependency_overrides:
    firebase_core_platform_interface: 4.5.1


 