name: taroting
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+14

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  camera: ^0.10.5+2
  chat_gpt_flutter: ^1.0.10
  firebase_core: ^2.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_tflite: ^1.0.1
  google_translator: ^1.0.0
  html_unescape: ^2.0.0
  language_picker: ^0.4.3
  image: ^3.3.0
  meta: ^1.8.0
  path_provider: ^2.0.15
  sharedor: 
    path: ../sharedor
  taroting_pk:
    path: ../taroting_pk
  # tflite: ^1.1.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"


flutter:
  uses-material-design: true
  fonts:
    - family: MartelSans
      fonts: 
      - asset: assets/fonts/MartelSans-Regular.ttf
    # - family: ZodiacSigns
    #   fonts: 
    #   - asset: assets/fonts/ZodiacSigns.ttf  
  assets:
    - assets/cards/
    - assets/camera-overlay-conceptcoder.png
    - assets/images/
dependency_overrides:
    # firebase_core_platform_interface: 4.5.1


 